    use customer_behaviour;
-- Q1.What is the total revenue generated by male vs female customers?
select gender, sum(Purchase_Amount) as total_revenue, count(*)
from customer_shopping_behavior
group by gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount?
select customerid, purchase_amount
from customer_shopping_behavior
where Discount_applied = 'Yes'
AND purchase_amount > (select avg(purchase_amount)
from customer_shopping_behavior);

-- Q3. Which are the top 5 products with the highest average review rating?
select Item_purchased, round(avg(review_rating),2) as avg_rating
from customer_shopping_behavior
group by Item_purchased
order by avg_rating desc
limit 5;

-- Q4. Compare the average purchase amounts between standard and express shipping.
select Shipping_Type, round(avg(Purchase_Amount),2) as avg_amt
from customer_shopping_behavior
where Shipping_Type in ('standard','express')
group by Shipping_Type;

-- Q5. Do subscribed customers spend more? compare avg spend and total revenue between subscribers and non-subscribers.
select Subscription_Status,
count(customerid) as total_customers, 
avg(Purchase_Amount) as avg_spend, 
sum(Purchase_Amount) as total_revenue
from customer_shopping_behavior
group by Subscription_Status
order by total_revenue, avg_spend desc;

-- Q6.which 5 products have the highest percentage of purchases with discounts applied?
select Item_Purchased,round(avg( case when discount_applied = 'yes' then 1 else 0 end)*100, 2) as Discount_percentage
from customer_shopping_behavior
group by Item_Purchased
order by  Discount_percentage desc
limit 5;
-- Q7. segment customers into new, returning, and loyal based on their total number of previous purchases, and show the count of each segment.
SELECT 
    CASE
        WHEN Previous_Purchases = 1 THEN 'New'
        WHEN
            Previous_Purchases > 2
                AND Previous_Purchases <= 10
        THEN'Returning'
        ELSE 'Loyal'
    END AS customer_segment,
    COUNT(*) AS number_of_customers
FROM
    customer_shopping_behavior
GROUP BY customer_segment;

-- Q8. what are the top 3 most purchased products within each category?
select * from 
(select category, item_Purchased, 
count(*) as purchased_count, 
rank() over (partition by category order by count(*) desc) as ranking
from customer_shopping_behavior
group by category,item_Purchased)
as ranked_table 
where ranking <= 3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select count(*) as total_repeat_buyers, sum(case when Subscription_Status = 'yes' then 1 else 0 end) as subscribers,
(sum(case when Subscription_Status = 'yes' then 1 else 0 end)/ count(*) * 100) Subscription_rate
from customer_shopping_behavior
where Previous_Purchases > 5;

-- Q10. what is the revenue contribution of each group?
SELECT 
    CASE 
        WHEN Previous_Purchases = 0 THEN 'New'
        WHEN Previous_Purchases > 0 AND Previous_Purchases <= 5 THEN 'Returning'
        ELSE 'Loyal' 
    END AS customer_segment,
    SUM(Purchase_Amount) AS total_revenue
FROM customer_shopping_behavior
GROUP BY customer_segment
ORDER BY total_revenue DESC;